import type { Banner } from "@/lib/slices/campaigns-slice";

export const mockCategories = [
  {
    id: "cat-1",
    name: "Pizzas",
    description: "Classic and specialty pizzas",
    sort: 1,
    showOn: { web: true, frontdesk: true },
  },
  {
    id: "cat-2",
    name: "Salads",
    description: "Fresh garden and specialty salads",
    sort: 2,
    showOn: { web: true, frontdesk: true },
  },
  {
    id: "cat-3",
    name: "Appetizers",
    description: "Starters and appetizers",
    sort: 3,
    showOn: { web: true, frontdesk: true },
  },
  {
    id: "cat-4",
    name: "Desserts",
    description: "Sweet treats and desserts",
    sort: 4,
    showOn: { web: true, frontdesk: false },
  },
  {
    id: "cat-5",
    name: "Beverages",
    description: "Drinks and beverages",
    sort: 5,
    showOn: { web: true, frontdesk: true },
  },
]

export const mockMenuItems = [
  {
    id: "item-1",
    categoryId: "cat-1",
    title: "Margherita Pizza",
    slug: "margherita-pizza",
    shortDesc: "Classic pizza with tomato, mozzarella, and basil",
    longDesc:
      "Our signature Margherita pizza made with fresh mozzarella, San Marzano tomatoes, and fresh basil on a thin crust.",
    badges: ["Vegetarian", "Popular"],
    taxIncluded: true,
    status: "PUBLISHED" as const,
    media: {
      imageUrl: "/margherita-pizza.png",
      alt: "Margherita Pizza",
    },
    availability: {
      global: "ALWAYS" as const,
    },
  },
  {
    id: "item-2",
    categoryId: "cat-2",
    title: "Caesar Salad",
    slug: "caesar-salad",
    shortDesc: "Crisp romaine with parmesan and croutons",
    longDesc:
      "Fresh romaine lettuce tossed with our house-made Caesar dressing, parmesan cheese, and homemade croutons.",
    badges: ["Vegetarian"],
    taxIncluded: true,
    status: "PUBLISHED" as const,
    media: {
      imageUrl: "/caesar-salad.png",
      alt: "Caesar Salad",
    },
    availability: {
      global: "ALWAYS" as const,
    },
  },
  {
    id: "item-3",
    categoryId: "cat-3",
    title: "Garlic Bread",
    slug: "garlic-bread",
    shortDesc: "Toasted bread with garlic butter and herbs",
    longDesc: "Crispy toasted bread brushed with garlic-infused butter and Italian herbs.",
    badges: ["Vegetarian"],
    taxIncluded: true,
    status: "PUBLISHED" as const,
    media: {
      imageUrl: "/garlic-bread.png",
      alt: "Garlic Bread",
    },
    availability: {
      global: "ALWAYS" as const,
    },
  },
  {
    id: "item-4",
    categoryId: "cat-1",
    title: "Pepperoni Pizza",
    slug: "pepperoni-pizza",
    shortDesc: "Classic pepperoni with mozzarella and tomato sauce",
    longDesc: "Traditional pepperoni pizza with premium mozzarella and our signature tomato sauce on a thin crust.",
    badges: ["Popular"],
    taxIncluded: true,
    status: "PUBLISHED" as const,
    media: {
      imageUrl: "/pepperoni-pizza.png",
      alt: "Pepperoni Pizza",
    },
    availability: {
      global: "ALWAYS" as const,
    },
  },
  {
    id: "item-5",
    categoryId: "cat-4",
    title: "Tiramisu",
    slug: "tiramisu",
    shortDesc: "Classic Italian dessert with mascarpone and espresso",
    longDesc: "Authentic tiramisu made with mascarpone cheese, espresso, and cocoa powder.",
    taxIncluded: true,
    status: "PUBLISHED" as const,
    media: {
      imageUrl: "/tiramisu.png",
      alt: "Tiramisu",
    },
    availability: {
      global: "SCHEDULED" as const,
    },
  },
  {
    id: "item-6",
    categoryId: "cat-5",
    title: "Coca Cola",
    slug: "coca-cola",
    shortDesc: "Classic Coca Cola soft drink",
    longDesc: "Ice-cold Coca Cola in your choice of sizes.",
    taxIncluded: true,
    status: "PUBLISHED" as const,
    availability: {
      global: "ALWAYS" as const,
    },
  },
  {
    id: "item-7",
    categoryId: "cat-1",
    title: "Vegetarian Pizza",
    slug: "vegetarian-pizza",
    shortDesc: "Pizza loaded with fresh vegetables",
    longDesc: "Delicious vegetarian pizza with bell peppers, mushrooms, olives, onions, and tomatoes.",
    badges: ["Vegetarian", "Vegan"],
    taxIncluded: true,
    status: "DRAFT" as const,
    media: {
      imageUrl: "/vegetarian-pizza.png",
      alt: "Vegetarian Pizza",
    },
    availability: {
      global: "ALWAYS" as const,
    },
  },
  {
    id: "item-8",
    categoryId: "cat-2",
    title: "Greek Salad",
    slug: "greek-salad",
    shortDesc: "Fresh salad with feta cheese and olives",
    longDesc: "Crisp vegetables with feta cheese, Kalamata olives, and Greek vinaigrette.",
    badges: ["Vegetarian"],
    taxIncluded: true,
    status: "PUBLISHED" as const,
    media: {
      imageUrl: "/greek-salad.png",
      alt: "Greek Salad",
    },
    availability: {
      global: "ALWAYS" as const,
    },
  },
]

export const mockOrders = [
  {
    id: "order-1",
    number: "#1001",
    status: "PREPARING" as const,
    placedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    branchId: "branch-1",
    customerName: "John Doe",
    total: 45.99,
    channel: "web" as const,
    paymentMethod: "card" as const,
    assignedRider: { id: "rider-1", name: "Mike Johnson", lastPingSec: 5 },
  },
  {
    id: "order-2",
    number: "#1002",
    status: "DISPATCHED" as const,
    placedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    branchId: "branch-1",
    customerName: "Jane Smith",
    total: 32.5,
    channel: "web" as const,
    paymentMethod: "wallet" as const,
    assignedRider: { id: "rider-2", name: "Sarah Williams", lastPingSec: 12 },
  },
  {
    id: "order-3",
    number: "#1003",
    status: "DELIVERED" as const,
    placedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    branchId: "branch-1",
    customerName: "Robert Johnson",
    total: 28.75,
    channel: "frontdesk" as const,
    paymentMethod: "cod" as const,
  },
  {
    id: "order-4",
    number: "#1004",
    status: "PENDING" as const,
    placedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    branchId: "branch-2",
    customerName: "Emily Davis",
    total: 56.2,
    channel: "web" as const,
    paymentMethod: "card" as const,
  },
  {
    id: "order-5",
    number: "#1005",
    status: "ACCEPTED" as const,
    placedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    branchId: "branch-1",
    customerName: "Michael Brown",
    total: 41.99,
    channel: "web" as const,
    paymentMethod: "card" as const,
  },
  {
    id: "order-6",
    number: "#1006",
    status: "READY" as const,
    placedAt: new Date(Date.now() - 35 * 60000).toISOString(),
    branchId: "branch-2",
    customerName: "Lisa Anderson",
    total: 38.5,
    channel: "frontdesk" as const,
    paymentMethod: "cod" as const,
  },
  {
    id: "order-7",
    number: "#1007",
    status: "CANCELLED" as const,
    placedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    branchId: "branch-1",
    customerName: "David Wilson",
    total: 22.99,
    channel: "web" as const,
    paymentMethod: "wallet" as const,
  },
  {
    id: "order-8",
    number: "#1008",
    status: "PREPARING" as const,
    placedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    branchId: "branch-2",
    customerName: "Sarah Martinez",
    total: 52.75,
    channel: "web" as const,
    paymentMethod: "card" as const,
    assignedRider: { id: "rider-3", name: "James Lee", lastPingSec: 8 },
  },
]

export const mockOrderDetail = {
  id: "order-1",
  number: "#1001",
  status: "PREPARING" as const,
  placedAt: new Date(Date.now() - 15 * 60000).toISOString(),
  branchId: "branch-1",
  customerName: "John Doe",
  total: 45.99,
  channel: "web" as const,
  paymentMethod: "card" as const,
  assignedRider: { id: "rider-1", name: "Mike Johnson", lastPingSec: 5 },
  items: [
    {
      itemId: "item-1",
      title: "Margherita Pizza",
      qty: 1,
      unitPrice: 14.99,
      modifiers: [
        { group: "Size", option: "Large", priceDelta: 2.0 },
        { group: "Crust", option: "Thin", priceDelta: 0 },
      ],
    },
    {
      itemId: "item-2",
      title: "Caesar Salad",
      qty: 2,
      unitPrice: 8.99,
      modifiers: [{ group: "Dressing", option: "Balsamic", priceDelta: 0 }],
    },
    {
      itemId: "item-3",
      title: "Garlic Bread",
      qty: 1,
      unitPrice: 4.99,
      modifiers: [],
    },
  ],
  notes: "Please ring the doorbell twice. No onions on the salad.",
  charges: {
    subtotal: 38.96,
    discount: 3.89,
    deliveryFee: 5.0,
    tax: 4.92,
    total: 45.99,
  },
  timeline: [
    { status: "PENDING" as const, at: new Date(Date.now() - 15 * 60000).toISOString() },
    { status: "ACCEPTED" as const, at: new Date(Date.now() - 12 * 60000).toISOString() },
    { status: "PREPARING" as const, at: new Date(Date.now() - 5 * 60000).toISOString() },
  ],
  customer: {
    id: "customer-1",
    name: "John Doe",
    phone: "+1 (555) 123-4567",
    email: "john.doe@example.com",
    lastOrderAt: new Date(Date.now() - 7 * 24 * 60 * 60000).toISOString(),
  },
  rider: {
    id: "rider-1",
    name: "Mike Johnson",
    phone: "+1 (555) 987-6543",
    status: "BUSY" as const,
    lastLocationAt: new Date(Date.now() - 30000).toISOString(),
    etaMin: 8,
  },
}

export const mockUsers = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@restaurant.com",
    role: "admin",
    status: "active" as const,
    lastLogin: "2025-10-20 14:30",
    createdAt: "2022-01-01",
  },
  {
    id: "user-2",
    name: "Manager User",
    email: "manager@restaurant.com",
    role: "manager",
    status: "active" as const,
    lastLogin: "2025-10-20 09:15",
    createdAt: "2023-03-15",
  },
  {
    id: "user-3",
    name: "Staff User",
    email: "staff@restaurant.com",
    role: "staff",
    status: "active" as const,
    lastLogin: "2025-10-19 18:45",
    createdAt: "2024-01-20",
  },
  {
    id: "user-4",
    name: "Inactive User",
    email: "inactive@restaurant.com",
    role: "staff",
    status: "inactive" as const,
    lastLogin: "2025-09-15 10:00",
    createdAt: "2024-06-10",
  },
]

export const mockFrontdeskStaff = [
  {
    id: "fd-1",
    name: "Sarah Johnson",
    role: "frontdesk" as const,
    email: "sarah.johnson@restaurant.com",
    lastPasswordChange: "2025-10-15",
  },
  {
    id: "fd-2",
    name: "Mike Chen",
    role: "frontdesk" as const,
    email: "mike.chen@restaurant.com",
    lastPasswordChange: "2025-09-20",
  },
  {
    id: "fd-3",
    name: "Emma Wilson",
    role: "frontdesk" as const,
    email: "emma.wilson@restaurant.com",
    lastPasswordChange: "2025-08-10",
  },
]

export const mockRiderStaff = [
  {
    id: "rider-1",
    name: "Alex Rodriguez",
    role: "rider" as const,
    email: "alex.rodriguez@restaurant.com",
    lastPasswordChange: "2025-10-10",
  },
  {
    id: "rider-2",
    name: "James Park",
    role: "rider" as const,
    email: "james.park@restaurant.com",
    lastPasswordChange: "2025-09-25",
  },
  {
    id: "rider-3",
    name: "Lisa Anderson",
    role: "rider" as const,
    email: "lisa.anderson@restaurant.com",
    lastPasswordChange: "2025-08-30",
  },
  {
    id: "rider-4",
    name: "David Kumar",
    role: "rider" as const,
    email: "david.kumar@restaurant.com",
    lastPasswordChange: "2025-07-15",
  },
]

export const mockRoles = [
  {
    id: "admin",
    name: "Administrator",
    description: "Full access to all features and settings",
    permissions: [
      "view_dashboard",
      "manage_orders",
      "manage_menu",
      "manage_staff",
      "manage_customers",
      "manage_campaigns",
      "view_reports",
      "manage_settings",
      "manage_users",
      "manage_roles",
    ],
    userCount: 1,
  },
  {
    id: "manager",
    name: "Manager",
    description: "Can manage orders, staff, and view reports",
    permissions: [
      "view_dashboard",
      "manage_orders",
      "manage_staff",
      "manage_customers",
      "view_reports",
      "manage_campaigns",
    ],
    userCount: 1,
  },
  {
    id: "staff",
    name: "Staff",
    description: "Can view orders and process them",
    permissions: ["view_dashboard", "manage_orders", "view_customers"],
    userCount: 2,
  },
  {
    id: "viewer",
    name: "Viewer",
    description: "Read-only access to dashboard and reports",
    permissions: ["view_dashboard", "view_reports"],
    userCount: 0,
  },
]

export const mockIntegrations = [
  {
    id: "int-1",
    name: "Stripe Payment",
    type: "payment" as const,
    status: "connected" as const,
    lastSync: "2025-10-20 14:30",
    config: { apiKey: "sk_live_***", webhookUrl: "https://api.restaurant.com/webhooks/stripe" },
  },
  {
    id: "int-2",
    name: "Google Analytics",
    type: "analytics" as const,
    status: "connected" as const,
    lastSync: "2025-10-20 14:25",
    config: { trackingId: "UA-***", propertyId: "G-***" },
  },
  {
    id: "int-3",
    name: "Twilio SMS",
    type: "communication" as const,
    status: "connected" as const,
    lastSync: "2025-10-20 14:20",
    config: { accountSid: "AC***", authToken: "***" },
  },
  {
    id: "int-4",
    name: "Delivery Partner API",
    type: "delivery" as const,
    status: "error" as const,
    lastSync: "2025-10-20 10:15",
    config: { apiEndpoint: "https://api.delivery.com", apiKey: "***" },
  },
]

export const mockKpis = {
  orders: 1247,
  revenue: 18540,
  aov: 14.87,
  prepTimeAvgMin: 12,
  deliveryTimeAvgMin: 28,
  activeRiders: 24,
  generatedAt: new Date().toISOString(),
}

export const mockTimeseries = {
  orders: [
    { bucket: "00:00", value: 45 },
    { bucket: "04:00", value: 12 },
    { bucket: "08:00", value: 156 },
    { bucket: "12:00", value: 289 },
    { bucket: "16:00", value: 234 },
    { bucket: "20:00", value: 321 },
    { bucket: "23:59", value: 190 },
  ],
  revenue: [
    { bucket: "00:00", value: 680 },
    { bucket: "04:00", value: 180 },
    { bucket: "08:00", value: 2340 },
    { bucket: "12:00", value: 4335 },
    { bucket: "16:00", value: 3510 },
    { bucket: "20:00", value: 4815 },
    { bucket: "23:59", value: 2860 },
  ],
  aov: [
    { bucket: "00:00", value: 15.11 },
    { bucket: "04:00", value: 15.0 },
    { bucket: "08:00", value: 15.0 },
    { bucket: "12:00", value: 15.0 },
    { bucket: "16:00", value: 15.0 },
    { bucket: "20:00", value: 15.0 },
    { bucket: "23:59", value: 15.05 },
  ],
}

export const mockPopularItem = {
  itemId: "item-1",
  title: "Margherita Pizza",
  units: 156,
  revenue: 1560,
  imageUrl: "/margherita-pizza.png",
}

export const mockLiveEvents = [
  {
    id: "1",
    type: "order.created" as const,
    title: "New order received",
    subtitle: "Order #1001 from John Doe",
    at: new Date().toISOString(),
  },
  {
    id: "2",
    type: "order.updated" as const,
    title: "Order delivered",
    subtitle: "Order #998 completed successfully",
    at: new Date().toISOString(),
  },
  {
    id: "3",
    type: "rider.capacity" as const,
    title: "Rider online",
    subtitle: "Rider John is now available",
    at: new Date().toISOString(),
  },
  {
    id: "4",
    type: "order.created" as const,
    title: "New order received",
    subtitle: "Order #1002 from Jane Smith",
    at: new Date().toISOString(),
  },
  {
    id: "5",
    type: "order.updated" as const,
    title: "Order out for delivery",
    subtitle: "Order #999 with rider Mike",
    at: new Date().toISOString(),
  },
]

export const mockReports = [
  {
    date: "2025-10-20",
    orders: 156,
    revenue: 2340,
    avgOrderValue: 15.0,
    customers: 142,
    topItems: [
      { name: "Margherita Pizza", quantity: 45, revenue: 674.55 },
      { name: "Pepperoni Pizza", quantity: 38, revenue: 569.62 },
      { name: "Caesar Salad", quantity: 32, revenue: 287.68 },
      { name: "Garlic Bread", quantity: 28, revenue: 139.72 },
      { name: "Coca Cola", quantity: 25, revenue: 62.5 },
    ],
  },
  {
    date: "2025-10-19",
    orders: 142,
    revenue: 2130,
    avgOrderValue: 15.0,
    customers: 128,
    topItems: [
      { name: "Margherita Pizza", quantity: 42, revenue: 629.58 },
      { name: "Pepperoni Pizza", quantity: 35, revenue: 524.65 },
      { name: "Caesar Salad", quantity: 28, revenue: 251.72 },
      { name: "Greek Salad", quantity: 22, revenue: 197.78 },
      { name: "Tiramisu", quantity: 18, revenue: 107.82 },
    ],
  },
  {
    date: "2025-10-18",
    orders: 168,
    revenue: 2520,
    avgOrderValue: 15.0,
    customers: 156,
    topItems: [
      { name: "Margherita Pizza", quantity: 52, revenue: 779.48 },
      { name: "Pepperoni Pizza", quantity: 44, revenue: 659.56 },
      { name: "Caesar Salad", quantity: 36, revenue: 323.64 },
      { name: "Garlic Bread", quantity: 32, revenue: 159.68 },
      { name: "Coca Cola", quantity: 28, revenue: 70.0 },
    ],
  },
  {
    date: "2025-10-17",
    orders: 134,
    revenue: 2010,
    avgOrderValue: 15.0,
    customers: 118,
    topItems: [
      { name: "Margherita Pizza", quantity: 38, revenue: 569.62 },
      { name: "Pepperoni Pizza", quantity: 32, revenue: 479.68 },
      { name: "Caesar Salad", quantity: 24, revenue: 215.76 },
      { name: "Greek Salad", quantity: 18, revenue: 161.82 },
      { name: "Garlic Bread", quantity: 20, revenue: 99.8 },
    ],
  },
  {
    date: "2025-10-16",
    orders: 178,
    revenue: 2670,
    avgOrderValue: 15.0,
    customers: 168,
    topItems: [
      { name: "Margherita Pizza", quantity: 58, revenue: 869.42 },
      { name: "Pepperoni Pizza", quantity: 48, revenue: 719.52 },
      { name: "Caesar Salad", quantity: 40, revenue: 359.6 },
      { name: "Garlic Bread", quantity: 36, revenue: 179.64 },
      { name: "Coca Cola", quantity: 32, revenue: 80.0 },
    ],
  },
  {
    date: "2025-10-15",
    orders: 145,
    revenue: 2175,
    avgOrderValue: 15.0,
    customers: 135,
    topItems: [
      { name: "Margherita Pizza", quantity: 44, revenue: 659.56 },
      { name: "Pepperoni Pizza", quantity: 36, revenue: 539.64 },
      { name: "Caesar Salad", quantity: 30, revenue: 269.7 },
      { name: "Greek Salad", quantity: 20, revenue: 179.8 },
      { name: "Tiramisu", quantity: 15, revenue: 89.85 },
    ],
  },
  {
    date: "2025-10-14",
    orders: 152,
    revenue: 2280,
    avgOrderValue: 15.0,
    customers: 142,
    topItems: [
      { name: "Margherita Pizza", quantity: 48, revenue: 719.52 },
      { name: "Pepperoni Pizza", quantity: 40, revenue: 599.6 },
      { name: "Caesar Salad", quantity: 34, revenue: 305.66 },
      { name: "Garlic Bread", quantity: 28, revenue: 139.72 },
      { name: "Coca Cola", quantity: 26, revenue: 65.0 },
    ],
  },
]

export const mockMetaAds = [
  {
    id: "ad-1",
    name: "Summer Pizza Special",
    platform: "facebook" as const,
    status: "active" as const,
    budget: 500,
    spent: 342.5,
    impressions: 12450,
    clicks: 287,
    conversions: 45,
    ctr: 2.3,
    cpc: 1.19,
    roas: 3.2,
    startDate: "2025-10-01",
    endDate: "2025-10-31",
  },
  {
    id: "ad-2",
    name: "Loyalty Program Launch",
    platform: "instagram" as const,
    status: "active" as const,
    budget: 300,
    spent: 298.75,
    impressions: 8920,
    clicks: 156,
    conversions: 28,
    ctr: 1.75,
    cpc: 1.92,
    roas: 2.8,
    startDate: "2025-10-10",
    endDate: "2025-10-25",
  },
  {
    id: "ad-3",
    name: "New Menu Items",
    platform: "both" as const,
    status: "active" as const,
    budget: 750,
    spent: 625.3,
    impressions: 18750,
    clicks: 412,
    conversions: 72,
    ctr: 2.2,
    cpc: 1.52,
    roas: 3.5,
    startDate: "2025-10-05",
    endDate: "2025-10-30",
  },
  {
    id: "ad-4",
    name: "Weekend Specials",
    platform: "facebook" as const,
    status: "paused" as const,
    budget: 400,
    spent: 156.8,
    impressions: 5230,
    clicks: 98,
    conversions: 12,
    ctr: 1.87,
    cpc: 1.6,
    roas: 2.1,
    startDate: "2025-10-15",
    endDate: "2025-10-22",
  },
  {
    id: "ad-5",
    name: "Flash Sale Campaign",
    platform: "instagram" as const,
    status: "ended" as const,
    budget: 250,
    spent: 250.0,
    impressions: 7650,
    clicks: 145,
    conversions: 22,
    ctr: 1.89,
    cpc: 1.72,
    roas: 2.6,
    startDate: "2025-09-20",
    endDate: "2025-10-05",
  },
]

export const mockCoupons = [
  {
    id: "coupon-1",
    code: "SUMMER20",
    type: "percentage" as const,
    value: 20,
    maxUses: 100,
    currentUses: 45,
    minOrderValue: 25,
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    isActive: true,
    description: "20% off on all orders above $25",
    applicableItems: ["item-1", "item-2", "item-3"],
  },
  {
    id: "coupon-2",
    code: "FLAT10",
    type: "fixed" as const,
    value: 10,
    maxUses: 50,
    currentUses: 28,
    minOrderValue: 30,
    startDate: new Date("2025-10-10"),
    endDate: new Date("2025-10-20"),
    isActive: true,
    description: "$10 off on orders above $30",
  },
  {
    id: "coupon-3",
    code: "WELCOME15",
    type: "percentage" as const,
    value: 15,
    maxUses: 200,
    currentUses: 156,
    minOrderValue: 20,
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-12-31"),
    isActive: true,
    description: "15% off for new customers",
  },
  {
    id: "coupon-4",
    code: "EXPIRED50",
    type: "percentage" as const,
    value: 50,
    maxUses: 100,
    currentUses: 100,
    minOrderValue: 50,
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-10-10"),
    isActive: false,
    description: "50% off - Expired",
  },
  {
    id: "coupon-5",
    code: "PIZZA25",
    type: "percentage" as const,
    value: 25,
    maxUses: 75,
    currentUses: 12,
    minOrderValue: 15,
    startDate: new Date("2025-10-15"),
    endDate: new Date("2025-10-25"),
    isActive: true,
    description: "25% off on pizza items",
    applicableItems: ["item-1", "item-4", "item-7"],
  },
]

export const mockPayments = [
  {
    id: "pay-1",
    orderId: "order-1",
    amount: 45.99,
    method: "card" as const,
    status: "completed" as const,
    transactionId: "txn_1234567890",
    processedAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "pay-2",
    orderId: "order-2",
    amount: 32.5,
    method: "wallet" as const,
    status: "completed" as const,
    transactionId: "txn_0987654321",
    processedAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: "pay-3",
    orderId: "order-3",
    amount: 28.75,
    method: "cod" as const,
    status: "pending" as const,
    transactionId: "txn_1111111111",
    processedAt: new Date(Date.now() - 120 * 60000).toISOString(),
  },
  {
    id: "pay-4",
    orderId: "order-4",
    amount: 56.2,
    method: "card" as const,
    status: "completed" as const,
    transactionId: "txn_2222222222",
    processedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: "pay-5",
    orderId: "order-5",
    amount: 41.99,
    method: "card" as const,
    status: "failed" as const,
    transactionId: "txn_3333333333",
    processedAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: "pay-6",
    orderId: "order-6",
    amount: 38.5,
    method: "wallet" as const,
    status: "refunded" as const,
    transactionId: "txn_4444444444",
    processedAt: new Date(Date.now() - 35 * 60000).toISOString(),
    refundedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    refundAmount: 38.5,
  },
]

export const mockBranches = [
  {
    id: "branch-1",
    name: "Downtown Branch",
    address: "123 Main Street",
    city: "New York",
    phone: "+1 (555) 123-4567",
    email: "downtown@restaurant.com",
    manager: "John Smith",
    status: "active" as const,
    openingTime: "10:00",
    closingTime: "23:00",
    latitude: 40.7128,
    longitude: -74.006,
    deliveryRadius: 5,
    createdAt: "2022-01-15",
  },
  {
    id: "branch-2",
    name: "Uptown Branch",
    address: "456 Park Avenue",
    city: "New York",
    phone: "+1 (555) 234-5678",
    email: "uptown@restaurant.com",
    manager: "Jane Doe",
    status: "active" as const,
    openingTime: "11:00",
    closingTime: "22:00",
    latitude: 40.7614,
    longitude: -73.9776,
    deliveryRadius: 4,
    createdAt: "2022-06-20",
  },
  {
    id: "branch-3",
    name: "Brooklyn Branch",
    address: "789 Brooklyn Road",
    city: "Brooklyn",
    phone: "+1 (555) 345-6789",
    email: "brooklyn@restaurant.com",
    manager: "Mike Johnson",
    status: "active" as const,
    openingTime: "10:30",
    closingTime: "23:30",
    latitude: 40.6782,
    longitude: -73.9442,
    deliveryRadius: 6,
    createdAt: "2023-03-10",
  },
  {
    id: "branch-4",
    name: "Queens Branch",
    address: "321 Queens Boulevard",
    city: "Queens",
    phone: "+1 (555) 456-7890",
    email: "queens@restaurant.com",
    manager: "Sarah Williams",
    status: "maintenance" as const,
    openingTime: "10:00",
    closingTime: "22:00",
    latitude: 40.7282,
    longitude: -73.7949,
    deliveryRadius: 5,
    createdAt: "2023-08-05",
  },
]

export const mockStaffInsights = [
  {
    id: "fd-1",
    name: "Sarah Johnson",
    role: "frontdesk" as const,
    totalOrders: 245,
    completedOrders: 240,
    averageRating: 4.8,
    hoursWorked: 160,
    performanceScore: 96,
  },
  {
    id: "fd-2",
    name: "Mike Chen",
    role: "frontdesk" as const,
    totalOrders: 198,
    completedOrders: 195,
    averageRating: 4.6,
    hoursWorked: 140,
    performanceScore: 92,
  },
  {
    id: "fd-3",
    name: "Emma Wilson",
    role: "frontdesk" as const,
    totalOrders: 167,
    completedOrders: 162,
    averageRating: 4.4,
    hoursWorked: 120,
    performanceScore: 85,
  },
  {
    id: "rider-1",
    name: "Alex Rodriguez",
    role: "rider" as const,
    totalOrders: 312,
    completedOrders: 308,
    averageRating: 4.9,
    hoursWorked: 180,
    performanceScore: 98,
  },
  {
    id: "rider-2",
    name: "James Park",
    role: "rider" as const,
    totalOrders: 287,
    completedOrders: 280,
    averageRating: 4.7,
    hoursWorked: 170,
    performanceScore: 94,
  },
  {
    id: "rider-3",
    name: "Lisa Anderson",
    role: "rider" as const,
    totalOrders: 256,
    completedOrders: 248,
    averageRating: 4.5,
    hoursWorked: 155,
    performanceScore: 88,
  },
  {
    id: "rider-4",
    name: "David Kumar",
    role: "rider" as const,
    totalOrders: 198,
    completedOrders: 185,
    averageRating: 4.2,
    hoursWorked: 140,
    performanceScore: 78,
  },
]

export const mockRiders = [
  {
    id: "rider-1",
    name: "Alex Rodriguez",
    phone: "+1 (555) 123-4567",
    status: "AVAILABLE" as const,
    activeOrders: 2,
    capacity: 5,
    lastPingSec: 8,
    vehicle: "bike" as const,
    branchId: "branch-1",
    rating: 4.9,
  },
  {
    id: "rider-2",
    name: "James Park",
    phone: "+1 (555) 234-5678",
    status: "BUSY" as const,
    activeOrders: 4,
    capacity: 5,
    lastPingSec: 15,
    vehicle: "car" as const,
    branchId: "branch-1",
    rating: 4.7,
  },
  {
    id: "rider-3",
    name: "Lisa Anderson",
    phone: "+1 (555) 345-6789",
    status: "AVAILABLE" as const,
    activeOrders: 1,
    capacity: 4,
    lastPingSec: 5,
    vehicle: "bike" as const,
    branchId: "branch-2",
    rating: 4.5,
  },
  {
    id: "rider-4",
    name: "David Kumar",
    phone: "+1 (555) 456-7890",
    status: "OFFLINE" as const,
    activeOrders: 0,
    capacity: 5,
    lastPingSec: 125,
    vehicle: "car" as const,
    branchId: "branch-2",
    rating: 4.2,
  },
  {
    id: "rider-5",
    name: "Maria Garcia",
    phone: "+1 (555) 567-8901",
    status: "AVAILABLE" as const,
    activeOrders: 3,
    capacity: 4,
    lastPingSec: 12,
    vehicle: "bike" as const,
    branchId: "branch-1",
    rating: 4.8,
  },
  {
    id: "rider-6",
    name: "John Smith",
    phone: "+1 (555) 678-9012",
    status: "BUSY" as const,
    activeOrders: 5,
    capacity: 5,
    lastPingSec: 22,
    vehicle: "car" as const,
    branchId: "branch-1",
    rating: 4.6,
  },
]

export const mockRiderProfile = {
  id: "rider-1",
  name: "Alex Rodriguez",
  phone: "+1 (555) 123-4567",
  status: "AVAILABLE" as const,
  activeOrders: 2,
  capacity: 5,
  lastPingSec: 8,
  vehicle: "bike" as const,
  branchId: "branch-1",
  rating: 4.9,
  docs: {
    cnicUrl: "/docs/cnic-rider-1.pdf",
    licenseUrl: "/docs/license-rider-1.pdf",
  },
  currentWork: {
    orders: [
      {
        orderId: "order-1001",
        stage: "EN_ROUTE_TO_CUSTOMER" as const,
        etaMin: 8,
        pickupAt: new Date(Date.now() - 10 * 60000).toISOString(),
        dropAt: undefined,
        customer: { name: "J*** D***", phone: "+1 (555) 1**-****" },
      },
      {
        orderId: "order-1002",
        stage: "PICKED_UP" as const,
        etaMin: 15,
        pickupAt: new Date(Date.now() - 5 * 60000).toISOString(),
        dropAt: undefined,
        customer: { name: "J*** S***", phone: "+1 (555) 2**-****" },
      },
    ],
    location: {
      lat: 40.7128,
      lng: -74.006,
      updatedAt: new Date(Date.now() - 30000).toISOString(),
    },
    route: {
      polyline: "encoded_polyline_string",
      distanceKm: 3.2,
      durationMin: 12,
    },
  },
  history: [
    {
      orderId: "order-998",
      deliveredAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
      onTime: true,
    },
    {
      orderId: "order-997",
      deliveredAt: new Date(Date.now() - 4 * 60 * 60000).toISOString(),
      onTime: true,
    },
    {
      orderId: "order-996",
      deliveredAt: new Date(Date.now() - 6 * 60 * 60000).toISOString(),
      onTime: false,
    },
    {
      orderId: "order-995",
      deliveredAt: new Date(Date.now() - 8 * 60 * 60000).toISOString(),
      onTime: true,
    },
    {
      orderId: "order-994",
      deliveredAt: new Date(Date.now() - 10 * 60 * 60000).toISOString(),
      onTime: true,
    },
  ],
  chats: [
    {
      id: "chat-1",
      orderId: "order-1001",
      channel: "inapp" as const,
      direction: "RIDER" as const,
      body: "I'm on my way, ETA 8 minutes",
      at: new Date(Date.now() - 5 * 60000).toISOString(),
    },
    {
      id: "chat-2",
      orderId: "order-1001",
      channel: "inapp" as const,
      direction: "ADMIN" as const,
      body: "Thanks for the update!",
      at: new Date(Date.now() - 4 * 60000).toISOString(),
    },
    {
      id: "chat-3",
      orderId: "order-1002",
      channel: "whatsapp" as const,
      direction: "CUSTOMER" as const,
      body: "Where is my order?",
      at: new Date(Date.now() - 3 * 60000).toISOString(),
    },
    {
      id: "chat-4",
      orderId: "order-1002",
      channel: "whatsapp" as const,
      direction: "RIDER" as const,
      body: "Picked up from restaurant, heading to you now",
      at: new Date(Date.now() - 2 * 60000).toISOString(),
    },
    {
      id: "chat-5",
      orderId: "order-998",
      channel: "sms" as const,
      direction: "ADMIN" as const,
      body: "Order delivered successfully",
      at: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    },
  ],
}




//Banners mock data 

export const mockBanners = [
  {
    id: "bnr-001",
    title: "Winter Mega Sale",
    description: "Up to 60% off on winter essentials.",
    imageUrl: "https://picsum.photos/seed/bnr-001/640/360",
    status: "active",
    position: "hero",
    impressions: 128540,
    clicks: 7432,
    startDate: "2025-10-01",
    endDate: "2025-12-31",
    link: "/deals/winter-mega-sale",
  },
  {
    id: "bnr-002",
    title: "New Arrivals • Streetwear",
    description: "Fresh drops every Friday.",
    imageUrl: "https://picsum.photos/seed/bnr-002/640/360",
    status: "active",
    position: "sidebar",
    impressions: 45890,
    clicks: 1986,
    startDate: "2025-09-15",
    endDate: "2025-11-30",
    link: "/collections/streetwear",
  },
  {
    id: "bnr-003",
    title: "Clearance • Last Chance",
    description: "Final markdowns on bestsellers.",
    imageUrl: "https://picsum.photos/seed/bnr-003/640/360",
    status: "inactive",
    position: "footer",
    impressions: 38912,
    clicks: 722,
    startDate: "2025-07-01",
    endDate: "2025-09-30",
    link: "/clearance",
  },
  {
    id: "bnr-004",
    title: "Festive Gifts Guide",
    description: "Thoughtful picks for everyone.",
    imageUrl: "https://picsum.photos/seed/bnr-004/640/360",
    status: "active",
    position: "hero",
    impressions: 97560,
    clicks: 6120,
    startDate: "2025-10-10",
    endDate: "2025-12-26",
    link: "/gifting",
  },
  {
    id: "bnr-005",
    title: "Electronics Weekend",
    description: "Limited-time bundles & combos.",
    imageUrl: "https://picsum.photos/seed/bnr-005/640/360",
    status: "active",
    position: "sidebar",
    impressions: 51234,
    clicks: 2354,
    startDate: "2025-10-18",
    endDate: "2025-11-02",
    link: "/collections/electronics",
  },
  {
    id: "bnr-006",
    title: "Home & Kitchen Refresh",
    description: "Makeover deals under $99.",
    imageUrl: "https://picsum.photos/seed/bnr-006/640/360",
    status: "inactive",
    position: "footer",
    impressions: 28670,
    clicks: 911,
    startDate: "2025-06-01",
    endDate: "2025-08-31",
    link: "/collections/home-kitchen",
  },
  {
    id: "bnr-007",
    title: "Member Exclusive",
    description: "Extra 10% off with login.",
    imageUrl: "https://picsum.photos/seed/bnr-007/640/360",
    status: "active",
    position: "hero",
    impressions: 80440,
    clicks: 4412,
    startDate: "2025-09-20",
    endDate: "2025-11-20",
    link: "/account/login?redirect=/deals/member-exclusive",
  },
  {
    id: "bnr-008",
    title: "Back to Campus",
    description: "Essentials for study & dorm.",
    imageUrl: "https://picsum.photos/seed/bnr-008/640/360",
    status: "inactive",
    position: "sidebar",
    impressions: 33550,
    clicks: 1065,
    startDate: "2025-07-20",
    endDate: "2025-09-10",
    link: "/collections/campus",
  },
  {
    id: "bnr-009",
    title: "Beauty • Buy 2 Get 1",
    description: "Mix & match self-care faves.",
    imageUrl: "https://picsum.photos/seed/bnr-009/640/360",
    status: "active",
    position: "footer",
    impressions: 40210,
    clicks: 1822,
    startDate: "2025-10-05",
    endDate: "2025-11-15",
    link: "/offers/beauty-b2g1",
  },
  {
    id: "bnr-010",
    title: "Sports & Outdoors",
    description: "Gear up for the season.",
    imageUrl: "https://picsum.photos/seed/bnr-010/640/360",
    status: "active",
    position: "hero",
    impressions: 69210,
    clicks: 3250,
    startDate: "2025-10-12",
    endDate: "2025-12-01",
    link: "/collections/outdoors",
  },
  {
    id: "bnr-011",
    title: "Work From Anywhere",
    description: "Laptops & accessories savings.",
    imageUrl: "https://picsum.photos/seed/bnr-011/640/360",
    status: "inactive",
    position: "sidebar",
    impressions: 24110,
    clicks: 590,
    startDate: "2025-04-10",
    endDate: "2025-06-30",
    link: "/collections/work-from-anywhere",
  },
  {
    id: "bnr-012",
    title: "Furniture Flash",
    description: "Big items, bigger discounts.",
    imageUrl: "https://picsum.photos/seed/bnr-012/640/360",
    status: "active",
    position: "footer",
    impressions: 31990,
    clicks: 1440,
    startDate: "2025-10-07",
    endDate: "2025-11-07",
    link: "/flash/furniture",
  },
  {
    id: "bnr-013",
    title: "Daily Deals Countdown",
    description: "New picks every 24 hours.",
    imageUrl: "https://picsum.photos/seed/bnr-013/640/360",
    status: "active",
    position: "hero",
    impressions: 88880,
    clicks: 5122,
    startDate: "2025-10-14",
    endDate: "2025-11-30",
    link: "/daily-deals",
  },
  {
    id: "bnr-014",
    title: "Pet Lovers’ Corner",
    description: "Treats, toys & essentials.",
    imageUrl: "https://picsum.photos/seed/bnr-014/640/360",
    status: "active",
    position: "sidebar",
    impressions: 27770,
    clicks: 1150,
    startDate: "2025-09-25",
    endDate: "2025-11-25",
    link: "/collections/pets",
  },
  {
    id: "bnr-015",
    title: "Smart Home Picks",
    description: "Automate your space.",
    imageUrl: "https://picsum.photos/seed/bnr-015/640/360",
    status: "inactive",
    position: "footer",
    impressions: 23150,
    clicks: 488,
    startDate: "2025-05-01",
    endDate: "2025-07-15",
    link: "/collections/smart-home",
  },
  {
    id: "bnr-016",
    title: "Gamer’s Paradise",
    description: "Consoles, titles & chairs.",
    imageUrl: "https://picsum.photos/seed/bnr-016/640/360",
    status: "active",
    position: "hero",
    impressions: 76440,
    clicks: 3920,
    startDate: "2025-10-09",
    endDate: "2025-12-15",
    link: "/collections/gaming",
  },
  {
    id: "bnr-017",
    title: "Boutique Fashion",
    description: "Handpicked looks you’ll love.",
    imageUrl: "https://picsum.photos/seed/bnr-017/640/360",
    status: "inactive",
    position: "sidebar",
    impressions: 18840,
    clicks: 420,
    startDate: "2025-03-01",
    endDate: "2025-05-31",
    link: "/collections/boutique",
  },
  {
    id: "bnr-018",
    title: "Books & Stationery",
    description: "Journal your season.",
    imageUrl: "https://picsum.photos/seed/bnr-018/640/360",
    status: "active",
    position: "footer",
    impressions: 26990,
    clicks: 1011,
    startDate: "2025-10-02",
    endDate: "2025-11-12",
    link: "/collections/books-stationery",
  },
  {
    id: "bnr-019",
    title: "Travel Essentials",
    description: "Bags, tags & gadgets.",
    imageUrl: "https://picsum.photos/seed/bnr-019/640/360",
    status: "active",
    position: "hero",
    impressions: 61220,
    clicks: 2840,
    startDate: "2025-10-03",
    endDate: "2025-12-20",
    link: "/collections/travel",
  },
  {
    id: "bnr-020",
    title: "Green Living",
    description: "Eco-swaps that stick.",
    imageUrl: "https://picsum.photos/seed/bnr-020/640/360",
    status: "active",
    position: "sidebar",
    impressions: 25500,
    clicks: 960,
    startDate: "2025-10-01",
    endDate: "2025-11-30",
    link: "/collections/eco",
  },
  {
    id: "bnr-021",
    title: "Kids’ Corner",
    description: "Toys & wearables for little ones.",
    imageUrl: "https://picsum.photos/seed/bnr-021/640/360",
    status: "inactive",
    position: "footer",
    impressions: 21440,
    clicks: 370,
    startDate: "2025-08-01",
    endDate: "2025-09-15",
    link: "/collections/kids",
  },
  {
    id: "bnr-022",
    title: "Luxury Picks",
    description: "Premium finds, special prices.",
    imageUrl: "https://picsum.photos/seed/bnr-022/640/360",
    status: "active",
    position: "hero",
    impressions: 70330,
    clicks: 3510,
    startDate: "2025-10-06",
    endDate: "2025-12-06",
    link: "/collections/luxury",
  },
  {
    id: "bnr-023",
    title: "DIY & Crafts",
    description: "Create something great.",
    imageUrl: "https://picsum.photos/seed/bnr-023/640/360",
    status: "inactive",
    position: "sidebar",
    impressions: 17660,
    clicks: 405,
    startDate: "2025-04-05",
    endDate: "2025-06-05",
    link: "/collections/diy",
  },
  {
    id: "bnr-024",
    title: "Automotive Essentials",
    description: "Keep your ride ready.",
    imageUrl: "https://picsum.photos/seed/bnr-024/640/360",
    status: "active",
    position: "footer",
    impressions: 30110,
    clicks: 1205,
    startDate: "2025-10-11",
    endDate: "2025-11-30",
    link: "/collections/auto",
  },
  {
    id: "bnr-025",
    title: "Health & Wellness",
    description: "Supplements and more.",
    imageUrl: "https://picsum.photos/seed/bnr-025/640/360",
    status: "active",
    position: "hero",
    impressions: 65550,
    clicks: 2894,
    startDate: "2025-10-04",
    endDate: "2025-12-04",
    link: "/collections/health",
  },
  {
    id: "bnr-026",
    title: "Music & Audio",
    description: "Headphones, speakers, mics.",
    imageUrl: "https://picsum.photos/seed/bnr-026/640/360",
    status: "active",
    position: "sidebar",
    impressions: 23880,
    clicks: 1008,
    startDate: "2025-09-28",
    endDate: "2025-11-28",
    link: "/collections/audio",
  },
  {
    id: "bnr-027",
    title: "Garden & Patio",
    description: "Outdoor living for less.",
    imageUrl: "https://picsum.photos/seed/bnr-027/640/360",
    status: "inactive",
    position: "footer",
    impressions: 16220,
    clicks: 305,
    startDate: "2025-05-10",
    endDate: "2025-07-20",
    link: "/collections/garden",
  },
  {
    id: "bnr-028",
    title: "Office Essentials",
    description: "Desk upgrades that matter.",
    imageUrl: "https://picsum.photos/seed/bnr-028/640/360",
    status: "active",
    position: "hero",
    impressions: 58110,
    clicks: 2604,
    startDate: "2025-10-08",
    endDate: "2025-12-08",
    link: "/collections/office",
  },
  {
    id: "bnr-029",
    title: "Photography Picks",
    description: "Cameras & lighting deals.",
    imageUrl: "https://picsum.photos/seed/bnr-029/640/360",
    status: "active",
    position: "sidebar",
    impressions: 22044,
    clicks: 980,
    startDate: "2025-10-13",
    endDate: "2025-11-30",
    link: "/collections/photography",
  },
  {
    id: "bnr-030",
    title: "Weekly Steals",
    description: "Handpicked bargains—updated weekly.",
    imageUrl: "https://picsum.photos/seed/bnr-030/640/360",
    status: "active",
    position: "footer",
    impressions: 34550,
    clicks: 1501,
    startDate: "2025-10-01",
    endDate: "2025-12-31",
    link: "/deals/weekly-steals",
  },
] satisfies Banner[];



//campagin list mock data

export const mockCampaigns = [
  {
    id: "cmp-001",
    name: "October Kickoff",
    description: "Start the month with sitewide savings.",
    status: "active",
    type: "discount",
    discountValue: 15,
    discountType: "percentage",
    minOrderValue: 25,
    usedCount: 432,
    maxUses: 2000,
    startDate: "2025-10-01",
    endDate: "2025-10-31",
  },
  {
    id: "cmp-002",
    name: "New User Welcome",
    description: "First order discount for newly registered users.",
    status: "active",
    type: "loyalty",
    discountValue: 10,
    discountType: "percentage",
    minOrderValue: 0,
    usedCount: 1180,
    maxUses: 5000,
    startDate: "2025-08-15",
    endDate: "2025-12-31",
  },
  {
    id: "cmp-003",
    name: "Refer & Earn",
    description: "Invite friends and both of you save.",
    status: "active",
    type: "referral",
    discountValue: 12,
    discountType: "percentage",
    minOrderValue: 30,
    usedCount: 640,
    maxUses: 3000,
    startDate: "2025-09-01",
    endDate: "2025-12-31",
  },
  {
    id: "cmp-004",
    name: "Clearance Boost",
    description: "Extra savings on clearance items.",
    status: "active",
    type: "discount",
    discountValue: 8,
    discountType: "fixed",
    minOrderValue: 40,
    usedCount: 950,
    maxUses: 5000,
    startDate: "2025-10-05",
    endDate: "2025-11-05",
  },
  {
    id: "cmp-005",
    name: "Fall Favorites",
    description: "Autumn picks at special prices.",
    status: "active",
    type: "seasonal",
    discountValue: 18,
    discountType: "percentage",
    minOrderValue: 50,
    usedCount: 220,
    maxUses: 1500,
    startDate: "2025-10-10",
    endDate: "2025-11-10",
  },
  {
    id: "cmp-006",
    name: "Cart Saver",
    description: "Nudge offer for abandoned carts.",
    status: "active",
    type: "discount",
    discountValue: 7,
    discountType: "fixed",
    minOrderValue: 20,
    usedCount: 410,
    maxUses: 4000,
    startDate: "2025-09-10",
    endDate: "2025-12-31",
  },
  {
    id: "cmp-007",
    name: "VIP Tier Bonus",
    description: "Extra perk for Gold members.",
    status: "active",
    type: "loyalty",
    discountValue: 20,
    discountType: "percentage",
    minOrderValue: 60,
    usedCount: 305,
    maxUses: 2000,
    startDate: "2025-09-20",
    endDate: "2025-12-20",
  },
  {
    id: "cmp-008",
    name: "Weekend Sprint",
    description: "Short 48h burst on select categories.",
    status: "active",
    type: "discount",
    discountValue: 5,
    discountType: "fixed",
    minOrderValue: 35,
    usedCount: 145,
    maxUses: 1200,
    startDate: "2025-10-18",
    endDate: "2025-10-21",
  },
  {
    id: "cmp-009",
    name: "Free Shipping Threshold",
    description: "Free shipping over a minimum spend.",
    status: "active",
    type: "discount",
    discountValue: 10,
    discountType: "fixed",
    minOrderValue: 75,
    usedCount: 980,
    maxUses: 7000,
    startDate: "2025-08-01",
    endDate: "2025-12-31",
  },
  {
    id: "cmp-010",
    name: "App Exclusive",
    description: "Mobile app-only special.",
    status: "active",
    type: "discount",
    discountValue: 12,
    discountType: "percentage",
    minOrderValue: 20,
    usedCount: 560,
    maxUses: 4000,
    startDate: "2025-09-05",
    endDate: "2025-11-30",
  },
  // Scheduled (future)
  {
    id: "cmp-011",
    name: "Singles’ Day Teaser",
    description: "Early-bird deals ahead of 11.11.",
    status: "scheduled",
    type: "seasonal",
    discountValue: 22,
    discountType: "percentage",
    minOrderValue: 50,
    usedCount: 0,
    maxUses: 5000,
    startDate: "2025-11-05",
    endDate: "2025-11-12",
  },
  {
    id: "cmp-012",
    name: "Black Friday Warm-up",
    description: "Pre Black Friday markdowns.",
    status: "scheduled",
    type: "seasonal",
    discountValue: 25,
    discountType: "percentage",
    minOrderValue: 60,
    usedCount: 0,
    maxUses: 8000,
    startDate: "2025-11-15",
    endDate: "2025-11-21",
  },
  {
    id: "cmp-013",
    name: "Black Friday",
    description: "The biggest sale of the year.",
    status: "scheduled",
    type: "seasonal",
    discountValue: 35,
    discountType: "percentage",
    minOrderValue: 0,
    usedCount: 0,
    maxUses: 20000,
    startDate: "2025-11-28",
    endDate: "2025-11-29",
  },
  {
    id: "cmp-014",
    name: "Cyber Monday",
    description: "One-day online blowout.",
    status: "scheduled",
    type: "seasonal",
    discountValue: 30,
    discountType: "percentage",
    minOrderValue: 0,
    usedCount: 0,
    maxUses: 18000,
    startDate: "2025-12-01",
    endDate: "2025-12-01",
  },
  {
    id: "cmp-015",
    name: "Holiday Gifting",
    description: "Gifts for everyone on your list.",
    status: "scheduled",
    type: "seasonal",
    discountValue: 20,
    discountType: "percentage",
    minOrderValue: 40,
    usedCount: 0,
    maxUses: 12000,
    startDate: "2025-12-05",
    endDate: "2025-12-24",
  },
  {
    id: "cmp-016",
    name: "Year-End Clearance",
    description: "Close out the year with deep discounts.",
    status: "scheduled",
    type: "discount",
    discountValue: 15,
    discountType: "fixed",
    minOrderValue: 70,
    usedCount: 0,
    maxUses: 9000,
    startDate: "2025-12-26",
    endDate: "2025-12-31",
  },
  {
    id: "cmp-017",
    name: "New Year, New You",
    description: "Kickstart resolutions with savings.",
    status: "scheduled",
    type: "seasonal",
    discountValue: 18,
    discountType: "percentage",
    minOrderValue: 35,
    usedCount: 0,
    maxUses: 10000,
    startDate: "2026-01-01",
    endDate: "2026-01-07",
  },
  {
    id: "cmp-018",
    name: "Referral January",
    description: "Boost referrals in Q1.",
    status: "scheduled",
    type: "referral",
    discountValue: 15,
    discountType: "percentage",
    minOrderValue: 25,
    usedCount: 0,
    maxUses: 6000,
    startDate: "2026-01-05",
    endDate: "2026-01-31",
  },
  {
    id: "cmp-019",
    name: "Loyalty Double Points",
    description: "Double points for members all month.",
    status: "scheduled",
    type: "loyalty",
    discountValue: 10,
    discountType: "percentage",
    minOrderValue: 20,
    usedCount: 0,
    maxUses: 7000,
    startDate: "2025-12-10",
    endDate: "2026-01-10",
  },
  {
    id: "cmp-020",
    name: "Weekend BOGOs",
    description: "Buy one, get one on select SKUs.",
    status: "scheduled",
    type: "discount",
    discountValue: 12,
    discountType: "percentage",
    minOrderValue: 30,
    usedCount: 0,
    maxUses: 4000,
    startDate: "2025-11-08",
    endDate: "2025-11-10",
  },
  // Ended (past)
  {
    id: "cmp-021",
    name: "Back to School",
    description: "Stationery and backpacks promo.",
    status: "ended",
    type: "seasonal",
    discountValue: 15,
    discountType: "percentage",
    minOrderValue: 20,
    usedCount: 2890,
    maxUses: 3000,
    startDate: "2025-08-01",
    endDate: "2025-09-10",
  },
  {
    id: "cmp-022",
    name: "Summer Sendoff",
    description: "Last call on summer styles.",
    status: "ended",
    type: "seasonal",
    discountValue: 20,
    discountType: "percentage",
    minOrderValue: 30,
    usedCount: 1780,
    maxUses: 2000,
    startDate: "2025-07-20",
    endDate: "2025-08-31",
  },
  {
    id: "cmp-023",
    name: "July Flash Deal",
    description: "48-hour sitewide coupon.",
    status: "ended",
    type: "discount",
    discountValue: 10,
    discountType: "fixed",
    minOrderValue: 50,
    usedCount: 980,
    maxUses: 1100,
    startDate: "2025-07-15",
    endDate: "2025-07-17",
  },
  {
    id: "cmp-024",
    name: "Spring Refresh",
    description: "Home & kitchen spring promo.",
    status: "ended",
    type: "seasonal",
    discountValue: 18,
    discountType: "percentage",
    minOrderValue: 40,
    usedCount: 3120,
    maxUses: 3500,
    startDate: "2025-04-01",
    endDate: "2025-05-15",
  },
  {
    id: "cmp-025",
    name: "Loyalty Onboarding",
    description: "Join the club and save.",
    status: "ended",
    type: "loyalty",
    discountValue: 8,
    discountType: "fixed",
    minOrderValue: 0,
    usedCount: 5200,
    maxUses: 5500,
    startDate: "2025-03-01",
    endDate: "2025-06-30",
  },
  {
    id: "cmp-026",
    name: "Referral Spring",
    description: "Seasonal referral drive.",
    status: "ended",
    type: "referral",
    discountValue: 10,
    discountType: "percentage",
    minOrderValue: 25,
    usedCount: 2100,
    maxUses: 2200,
    startDate: "2025-04-10",
    endDate: "2025-05-10",
  },
  {
    id: "cmp-027",
    name: "Q2 Cart Rescue",
    description: "Abandoned cart incentive.",
    status: "ended",
    type: "discount",
    discountValue: 6,
    discountType: "fixed",
    minOrderValue: 20,
    usedCount: 1490,
    maxUses: 2000,
    startDate: "2025-05-01",
    endDate: "2025-06-30",
  },
  {
    id: "cmp-028",
    name: "Midsummer Loyalty",
    description: "Extra points on apparel.",
    status: "ended",
    type: "loyalty",
    discountValue: 12,
    discountType: "percentage",
    minOrderValue: 30,
    usedCount: 1750,
    maxUses: 1800,
    startDate: "2025-06-15",
    endDate: "2025-07-15",
  },
  {
    id: "cmp-029",
    name: "Early Autumn Teaser",
    description: "Warm up to fall savings.",
    status: "ended",
    type: "seasonal",
    discountValue: 14,
    discountType: "percentage",
    minOrderValue: 20,
    usedCount: 990,
    maxUses: 1000,
    startDate: "2025-09-05",
    endDate: "2025-09-20",
  },
  {
    id: "cmp-030",
    name: "September Payday",
    description: "Payday weekend offers.",
    status: "ended",
    type: "discount",
    discountValue: 9,
    discountType: "fixed",
    minOrderValue: 45,
    usedCount: 1300,
    maxUses: 1500,
    startDate: "2025-09-25",
    endDate: "2025-09-28",
  },
];


//customer mock data



export type CustomerStatus = "active" | "inactive" | "vip";

export interface Review {
  id: string;
  rating: number;    // 1..5
  comment: string;
  date: string;      // YYYY-MM-DD
}

export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  status: CustomerStatus;
  totalOrders: number;
  totalSpent: number;     // used with toFixed(2) in UI
  averageRating: number;  // e.g. 4.6
  joinDate?: string;      // optional
  lastOrderDate?: string; // optional
  reviews?: Review[];     // optional
}

export const mockCustomers = [
  { id: "cus-001", name: "Ayesha Khan",  email: "ayesha.khan@example.com",  phone: "+92 300 111 0001", status: "vip",     totalOrders: 42, totalSpent: 5890.75, averageRating: 4.9, joinDate: "2024-03-10", lastOrderDate: "2025-10-15", reviews: [] },
  { id: "cus-002", name: "Ali Raza",     email: "ali.raza@example.com",     phone: "+92 301 111 0002", status: "active",  totalOrders: 18, totalSpent: 1250.00, averageRating: 4.3, joinDate: "2024-05-22", lastOrderDate: "2025-10-12", reviews: [] },
  { id: "cus-003", name: "Fatima Noor",  email: "fatima.noor@example.com",  phone: "+92 302 111 0003", status: "active",  totalOrders:  9, totalSpent:  420.49, averageRating: 4.7, joinDate: "2025-01-09", lastOrderDate: "2025-10-08", reviews: [] },
  { id: "cus-004", name: "Zain Ahmed",   email: "zain.ahmed@example.com",   phone: "+92 303 111 0004", status: "inactive",totalOrders:  3, totalSpent:  118.99, averageRating: 3.8, joinDate: "2023-11-02", lastOrderDate: "2025-06-21", reviews: [] },
  { id: "cus-005", name: "Hira Siddiqui",email: "hira.siddiqui@example.com",phone: "+92 304 111 0005", status: "vip",     totalOrders: 55, totalSpent: 8123.10, averageRating: 4.8, joinDate: "2023-12-15", lastOrderDate: "2025-10-18", reviews: [] },
  { id: "cus-006", name: "Omar Farooq",  email: "omar.farooq@example.com",  phone: "+92 305 111 0006", status: "active",  totalOrders: 15, totalSpent:  980.00, averageRating: 4.1, joinDate: "2024-07-01", lastOrderDate: "2025-09-29", reviews: [] },
  { id: "cus-007", name: "Maryam Ali",   email: "maryam.ali@example.com",   phone: "+92 306 111 0007", status: "active",  totalOrders: 22, totalSpent: 2035.60, averageRating: 4.6, joinDate: "2024-02-20", lastOrderDate: "2025-10-17", reviews: [] },
  { id: "cus-008", name: "Hassan Javed", email: "hassan.javed@example.com", phone: "+92 307 111 0008", status: "inactive",totalOrders:  1, totalSpent:   35.00, averageRating: 3.2, joinDate: "2025-02-11", lastOrderDate: "2025-03-03", reviews: [] },
  { id: "cus-009", name: "Noor Zehra",   email: "noor.zehra@example.com",   phone: "+92 308 111 0009", status: "vip",     totalOrders: 38, totalSpent: 5310.35, averageRating: 4.9, joinDate: "2023-10-05", lastOrderDate: "2025-10-16", reviews: [] },
  { id: "cus-010", name: "Bilal Hussain",email: "bilal.hussain@example.com",phone: "+92 309 111 0010", status: "active",  totalOrders: 11, totalSpent:  705.10, averageRating: 4.0, joinDate: "2024-09-09", lastOrderDate: "2025-10-10", reviews: [] },

  { id: "cus-011", name: "Sana Tariq",   email: "sana.tariq@example.com",   phone: "+92 300 111 0011", status: "active",  totalOrders: 17, totalSpent: 1299.99, averageRating: 4.5, joinDate: "2024-06-14", lastOrderDate: "2025-10-11", reviews: [] },
  { id: "cus-012", name: "Ahmad Rauf",   email: "ahmad.rauf@example.com",   phone: "+92 301 111 0012", status: "inactive",totalOrders:  2, totalSpent:   79.50, averageRating: 3.6, joinDate: "2023-09-23", lastOrderDate: "2025-02-07", reviews: [] },
  { id: "cus-013", name: "Laiba Shah",   email: "laiba.shah@example.com",   phone: "+92 302 111 0013", status: "vip",     totalOrders: 64, totalSpent: 9740.00, averageRating: 5.0, joinDate: "2022-12-01", lastOrderDate: "2025-10-19", reviews: [] },
  { id: "cus-014", name: "Usman Aslam",  email: "usman.aslam@example.com",  phone: "+92 303 111 0014", status: "active",  totalOrders: 24, totalSpent: 2150.25, averageRating: 4.4, joinDate: "2024-01-18", lastOrderDate: "2025-10-06", reviews: [] },
  { id: "cus-015", name: "Iqra Yousaf",  email: "iqra.yousaf@example.com",  phone: "+92 304 111 0015", status: "active",  totalOrders: 13, totalSpent:  890.35, averageRating: 4.2, joinDate: "2025-03-03", lastOrderDate: "2025-09-27", reviews: [] },
  { id: "cus-016", name: "Daniyal Khan", email: "daniyal.khan@example.com", phone: "+92 305 111 0016", status: "inactive",totalOrders:  4, totalSpent:  150.00, averageRating: 3.9, joinDate: "2023-08-08", lastOrderDate: "2025-01-29", reviews: [] },
  { id: "cus-017", name: "Mishal Rehman",email: "mishal.rehman@example.com",phone: "+92 306 111 0017", status: "vip",     totalOrders: 47, totalSpent: 6820.80, averageRating: 4.8, joinDate: "2024-04-22", lastOrderDate: "2025-10-14", reviews: [] },
  { id: "cus-018", name: "Talha Nadeem", email: "talha.nadeem@example.com", phone: "+92 307 111 0018", status: "active",  totalOrders: 19, totalSpent: 1395.00, averageRating: 4.3, joinDate: "2024-10-01", lastOrderDate: "2025-10-13", reviews: [] },
  { id: "cus-019", name: "Haleema Saeed",email: "haleema.saeed@example.com",phone: "+92 308 111 0019", status: "active",  totalOrders:  8, totalSpent:  360.70, averageRating: 4.1, joinDate: "2025-05-12", lastOrderDate: "2025-09-10", reviews: [] },
  { id: "cus-020", name: "Rehan Qureshi",email: "rehan.qureshi@example.com",phone: "+92 309 111 0020", status: "inactive",totalOrders:  2, totalSpent:   64.20, averageRating: 3.4, joinDate: "2023-10-30", lastOrderDate: "2024-12-19", reviews: [] },

  { id: "cus-021", name: "Areeba Sheikh",email: "areeba.sheikh@example.com",phone: "+92 300 111 0021", status: "vip",     totalOrders: 51, totalSpent: 7444.90, averageRating: 4.9, joinDate: "2023-06-06", lastOrderDate: "2025-10-18", reviews: [] },
  { id: "cus-022", name: "Hamza Gul",    email: "hamza.gul@example.com",    phone: "+92 301 111 0022", status: "active",  totalOrders: 16, totalSpent: 1120.00, averageRating: 4.2, joinDate: "2024-11-02", lastOrderDate: "2025-10-09", reviews: [] },
  { id: "cus-023", name: "Zoya Imran",   email: "zoya.imran@example.com",   phone: "+92 302 111 0023", status: "active",  totalOrders: 27, totalSpent: 2495.55, averageRating: 4.6, joinDate: "2024-02-11", lastOrderDate: "2025-10-16", reviews: [] },
  { id: "cus-024", name: "Salman Iqbal", email: "salman.iqbal@example.com", phone: "+92 303 111 0024", status: "inactive",totalOrders:  5, totalSpent:  210.00, averageRating: 3.7, joinDate: "2023-09-12", lastOrderDate: "2025-03-15", reviews: [] },
  { id: "cus-025", name: "Mehwish Akhtar",email:"mehwish.akhtar@example.com",phone:"+92 304 111 0025", status: "vip",     totalOrders: 58, totalSpent: 8888.88, averageRating: 4.9, joinDate: "2022-11-19", lastOrderDate: "2025-10-17", reviews: [] },
  { id: "cus-026", name: "Saad Latif",   email: "saad.latif@example.com",   phone: "+92 305 111 0026", status: "active",  totalOrders: 14, totalSpent:  975.25, averageRating: 4.0, joinDate: "2025-02-02", lastOrderDate: "2025-09-25", reviews: [] },
  { id: "cus-027", name: "Hiba Raza",    email: "hiba.raza@example.com",    phone: "+92 306 111 0027", status: "active",  totalOrders: 21, totalSpent: 1890.40, averageRating: 4.5, joinDate: "2024-03-27", lastOrderDate: "2025-10-05", reviews: [] },
  { id: "cus-028", name: "Shahzad Malik",email: "shahzad.malik@example.com",phone: "+92 307 111 0028", status: "inactive",totalOrders:  3, totalSpent:  129.99, averageRating: 3.5, joinDate: "2023-07-07", lastOrderDate: "2024-11-30", reviews: [] },
  { id: "cus-029", name: "Nimra Junaid", email: "nimra.junaid@example.com", phone: "+92 308 111 0029", status: "active",  totalOrders: 10, totalSpent:  560.00, averageRating: 4.2, joinDate: "2025-06-21", lastOrderDate: "2025-10-01", reviews: [] },
  { id: "cus-030", name: "Taimoor Anwar",email: "taimoor.anwar@example.com",phone: "+92 309 111 0030", status: "vip",     totalOrders: 44, totalSpent: 6110.05, averageRating: 4.7, joinDate: "2023-05-25", lastOrderDate: "2025-10-12", reviews: [] },
] satisfies Customer[];




//mockStaff
export const mockStaff = [
  {
    id: "stf-001",
    name: "Sarah Johnson",
    email: "sarah.johnson@restaurant.com",
    phone: "+92 300 0000001",
    status: "active" as const,
    role: "manager" as const,
    performance: { ordersProcessed: 1240, accuracy: 98.2, avgRating: 4.9 },
  },
  {
    id: "stf-002",
    name: "Mike Chen",
    email: "mike.chen@restaurant.com",
    phone: "+92 300 0000002",
    status: "active" as const,
    role: "cashier" as const,
    performance: { ordersProcessed: 980, accuracy: 96.5, avgRating: 4.7 },
  },
  {
    id: "stf-003",
    name: "Emma Wilson",
    email: "emma.wilson@restaurant.com",
    phone: "+92 300 0000003",
    status: "on-leave" as const,
    role: "kitchen" as const,
    performance: { ordersProcessed: 610, accuracy: 94.1, avgRating: 4.5 },
  },
  {
    id: "stf-004",
    name: "Alex Rodriguez",
    email: "alex.rodriguez@restaurant.com",
    phone: "+92 300 0000004",
    status: "active" as const,
    role: "delivery" as const,
    performance: { ordersProcessed: 1535, accuracy: 97.6, avgRating: 4.8 },
  },
  {
    id: "stf-005",
    name: "Hina Asif",
    email: "hina.asif@restaurant.com",
    phone: "+92 300 0000005",
    status: "inactive" as const,
    role: "cashier" as const,
    performance: { ordersProcessed: 220, accuracy: 92.3, avgRating: 4.0 },
  },
  {
    id: "stf-006",
    name: "Naveed Khan",
    email: "naveed.khan@restaurant.com",
    phone: "+92 300 0000006",
    status: "active" as const,
    role: "manager" as const,
    performance: { ordersProcessed: 1095, accuracy: 97.9, avgRating: 4.8 },
  },
  {
    id: "stf-007",
    name: "Zara Rehman",
    email: "zara.rehman@restaurant.com",
    phone: "+92 300 0000007",
    status: "active" as const,
    role: "delivery" as const,
    performance: { ordersProcessed: 1320, accuracy: 95.8, avgRating: 4.6 },
  },
  {
    id: "stf-008",
    name: "Talal Sheikh",
    email: "talal.sheikh@restaurant.com",
    phone: "+92 300 0000008",
    status: "active" as const,
    role: "kitchen" as const,
    performance: { ordersProcessed: 780, accuracy: 96.1, avgRating: 4.4 },
  },
  {
    id: "stf-009",
    name: "Eman Tariq",
    email: "eman.tariq@restaurant.com",
    phone: "+92 300 0000009",
    status: "on-leave" as const,
    role: "cashier" as const,
    performance: { ordersProcessed: 360, accuracy: 93.5, avgRating: 4.2 },
  },
  {
    id: "stf-010",
    name: "Owais Memon",
    email: "owais.memon@restaurant.com",
    phone: "+92 300 0000010",
    status: "active" as const,
    role: "frontdesk" as const,
    performance: { ordersProcessed: 905, accuracy: 96.2, avgRating: 4.5 },
  },
  {
    id: "stf-011",
    name: "Ibrahim Rizvi",
    email: "ibrahim.rizvi@restaurant.com",
    phone: "+92 300 0000011",
    status: "inactive" as const,
    role: "delivery" as const,
    performance: { ordersProcessed: 410, accuracy: 91.8, avgRating: 4.1 },
  },
  {
    id: "stf-012",
    name: "Mina Aftab",
    email: "mina.aftab@restaurant.com",
    phone: "+92 300 0000012",
    status: "active" as const,
    role: "kitchen" as const,
    performance: { ordersProcessed: 845, accuracy: 95.5, avgRating: 4.6 },
  },
  {
    id: "stf-013",
    name: "Javeria Anwar",
    email: "javeria.anwar@restaurant.com",
    phone: "+92 300 0000013",
    status: "active" as const,
    role: "cashier" as const,
    performance: { ordersProcessed: 760, accuracy: 96.0, avgRating: 4.6 },
  },
  {
    id: "stf-014",
    name: "Faizan Raza",
    email: "faizan.raza@restaurant.com",
    phone: "+92 300 0000014",
    status: "active" as const,
    role: "delivery" as const,
    performance: { ordersProcessed: 1275, accuracy: 97.2, avgRating: 4.7 },
  },
  {
    id: "stf-015",
    name: "Haris Jameel",
    email: "haris.jameel@restaurant.com",
    phone: "+92 300 0000015",
    status: "on-leave" as const,
    role: "manager" as const,
    performance: { ordersProcessed: 680, accuracy: 94.9, avgRating: 4.3 },
  },
  {
    id: "stf-016",
    name: "Aqsa Younas",
    email: "aqsa.younas@restaurant.com",
    phone: "+92 300 0000016",
    status: "active" as const,
    role: "kitchen" as const,
    performance: { ordersProcessed: 910, accuracy: 96.8, avgRating: 4.7 },
  },
  {
    id: "stf-017",
    name: "Usman Tariq",
    email: "usman.tariq@restaurant.com",
    phone: "+92 300 0000017",
    status: "inactive" as const,
    role: "cashier" as const,
    performance: { ordersProcessed: 295, accuracy: 92.1, avgRating: 4.0 },
  },
  {
    id: "stf-018",
    name: "Noor Fatima",
    email: "noor.fatima@restaurant.com",
    phone: "+92 300 0000018",
    status: "active" as const,
    role: "manager" as const,
    performance: { ordersProcessed: 1015, accuracy: 98.0, avgRating: 4.9 },
  },
  {
    id: "stf-019",
    name: "Danish Khan",
    email: "danish.khan@restaurant.com",
    phone: "+92 300 0000019",
    status: "active" as const,
    role: "delivery" as const,
    performance: { ordersProcessed: 1110, accuracy: 95.1, avgRating: 4.5 },
  },
  {
    id: "stf-020",
    name: "Sana Ali",
    email: "sana.ali@restaurant.com",
    phone: "+92 300 0000020",
    status: "active" as const,
    role: "cashier" as const,
    performance: { ordersProcessed: 830, accuracy: 96.7, avgRating: 4.6 },
  },
] as const;